# Generated by Django 5.0 on 2025-08-03 15:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        ("shops", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="useratmospherepreference",
            name="indicator",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="shops.atmosphereindicator",
            ),
        ),
        migrations.AddField(
            model_name="useratmospherepreference",
            name="user_profile",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="atmosphere_preferences",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="useraccount",
            name="visit_purposes",
            field=models.ManyToManyField(
                blank=True, related_name="users", to="accounts.visitpurpose"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="alcoholbrand",
            unique_together={("name", "category")},
        ),
        migrations.AlterUniqueTogether(
            name="drinkstyle",
            unique_together={("name", "category")},
        ),
        migrations.AlterUniqueTogether(
            name="interest",
            unique_together={("name", "category")},
        ),
        migrations.AlterUniqueTogether(
            name="useratmospherepreference",
            unique_together={("user_profile", "indicator")},
        ),
    ]
