# Generated by Django 4.2.20 on 2025-06-27 05:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_usertag_useraccount_birthdate_useraccount_gender_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Alcohol",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "好きなお酒・ドリンク",
                "verbose_name_plural": "好きなお酒・ドリンク",
            },
        ),
        migrations.CreateModel(
            name="BloodType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "血液型",
                "verbose_name_plural": "血液型",
            },
        ),
        migrations.CreateModel(
            name="ExerciseHabit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "運動",
                "verbose_name_plural": "運動",
            },
        ),
        migrations.CreateModel(
            name="Hobby",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "趣味",
                "verbose_name_plural": "趣味",
            },
        ),
        migrations.CreateModel(
            name="InterestCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "興味カテゴリ",
                "verbose_name_plural": "興味カテゴリ",
            },
        ),
        migrations.CreateModel(
            name="MBTI",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "MBTI",
                "verbose_name_plural": "MBTI",
            },
        ),
        migrations.CreateModel(
            name="SocialPreference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "交友関係",
                "verbose_name_plural": "交友関係",
            },
        ),
        migrations.AddField(
            model_name="useraccount",
            name="work_info",
            field=models.TextField(blank=True, null=True, verbose_name="仕事情報"),
        ),
        migrations.CreateModel(
            name="Interest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="interests",
                        to="accounts.interestcategory",
                    ),
                ),
            ],
            options={
                "verbose_name": "興味",
                "verbose_name_plural": "興味",
            },
        ),
        migrations.AddField(
            model_name="useraccount",
            name="alcohols",
            field=models.ManyToManyField(
                blank=True, related_name="users", to="accounts.alcohol"
            ),
        ),
        migrations.AddField(
            model_name="useraccount",
            name="blood_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="users",
                to="accounts.bloodtype",
            ),
        ),
        migrations.AddField(
            model_name="useraccount",
            name="exercise_habits",
            field=models.ManyToManyField(
                blank=True, related_name="users", to="accounts.exercisehabit"
            ),
        ),
        migrations.AddField(
            model_name="useraccount",
            name="hobbies",
            field=models.ManyToManyField(
                blank=True, related_name="users", to="accounts.hobby"
            ),
        ),
        migrations.AddField(
            model_name="useraccount",
            name="interests",
            field=models.ManyToManyField(
                blank=True, related_name="users", to="accounts.interest"
            ),
        ),
        migrations.AddField(
            model_name="useraccount",
            name="mbti",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="users",
                to="accounts.mbti",
            ),
        ),
        migrations.AddField(
            model_name="useraccount",
            name="social_preferences",
            field=models.ManyToManyField(
                blank=True, related_name="users", to="accounts.socialpreference"
            ),
        ),
    ]
