# Generated by Django 5.0 on 2025-08-08 06:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProfileVisibilitySettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("age", models.BooleanField(default=True, verbose_name="年齢公開")),
                (
                    "my_area",
                    models.BooleanField(default=True, verbose_name="マイエリア公開"),
                ),
                (
                    "interests",
                    models.BooleanField(default=True, verbose_name="興味公開"),
                ),
                (
                    "blood_type",
                    models.BooleanField(default=True, verbose_name="血液型公開"),
                ),
                ("mbti", models.BooleanField(default=True, verbose_name="MBTI公開")),
                (
                    "occupation",
                    models.BooleanField(default=True, verbose_name="職業公開"),
                ),
                (
                    "industry",
                    models.BooleanField(default=True, verbose_name="業種公開"),
                ),
                (
                    "position",
                    models.BooleanField(default=True, verbose_name="役職公開"),
                ),
                (
                    "alcohol_preferences",
                    models.BooleanField(default=True, verbose_name="お酒の好み公開"),
                ),
                ("hobbies", models.BooleanField(default=True, verbose_name="趣味公開")),
                (
                    "exercise_frequency",
                    models.BooleanField(default=True, verbose_name="運動頻度公開"),
                ),
                (
                    "dietary_preference",
                    models.BooleanField(
                        default=True, verbose_name="食事制限・好み公開"
                    ),
                ),
                (
                    "atmosphere_preferences",
                    models.BooleanField(default=True, verbose_name="雰囲気の好み公開"),
                ),
                (
                    "visit_purposes",
                    models.BooleanField(default=True, verbose_name="利用目的公開"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成日"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日"),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="visibility_settings",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="ユーザー",
                    ),
                ),
            ],
            options={
                "verbose_name": "プロフィール公開設定",
                "verbose_name_plural": "プロフィール公開設定",
            },
        ),
    ]
