# Generated by Django 5.0 on 2025-06-30 03:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_alcohol_bloodtype_exercisehabit_hobby_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userusertag",
            name="user_tag",
        ),
        migrations.RemoveField(
            model_name="userusertag",
            name="user",
        ),
        migrations.DeleteModel(
            name="UserTag",
        ),
        migrations.DeleteModel(
            name="UserUserTag",
        ),
    ]
