# Generated by Django 5.0 on 2025-08-08 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_profilevisibilitysettings"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profilevisibilitysettings",
            name="my_area",
        ),
    ]
