# Generated by Django 4.2.20 on 2025-07-18 05:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "accounts",
            "0004_remove_userusertag_user_tag_remove_userusertag_user_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="AlcoholCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "お酒のジャンル",
                "verbose_name_plural": "お酒のジャンル",
            },
        ),
        migrations.CreateModel(
            name="DrinkStyle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="drink_styles",
                        to="accounts.alcoholcategory",
                    ),
                ),
            ],
            options={
                "verbose_name": "カクテル・飲み方",
                "verbose_name_plural": "カクテル・飲み方",
            },
        ),
        migrations.CreateModel(
            name="AlcoholBrand",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="brands",
                        to="accounts.alcoholcategory",
                    ),
                ),
            ],
            options={
                "verbose_name": "お酒の銘柄",
                "verbose_name_plural": "お酒の銘柄",
            },
        ),
        migrations.AddField(
            model_name="useraccount",
            name="alcohol_brands",
            field=models.ManyToManyField(
                blank=True, related_name="users", to="accounts.alcoholbrand"
            ),
        ),
        migrations.AddField(
            model_name="useraccount",
            name="alcohol_categories",
            field=models.ManyToManyField(
                blank=True, related_name="users", to="accounts.alcoholcategory"
            ),
        ),
        migrations.AddField(
            model_name="useraccount",
            name="drink_styles",
            field=models.ManyToManyField(
                blank=True, related_name="users", to="accounts.drinkstyle"
            ),
        ),
    ]
