# Generated by Django 5.0 on 2025-08-16 13:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_remove_profilevisibilitysettings_my_area"),
        ("shops", "0002_area_alter_shop_area_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="useraccount",
            name="my_areas",
            field=models.ManyToManyField(
                blank=True,
                related_name="users",
                to="shops.area",
                verbose_name="マイエリア",
            ),
        ),
        migrations.AddField(
            model_name="useraccount",
            name="primary_area",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="primary_users",
                to="shops.area",
                verbose_name="メインエリア",
            ),
        ),
    ]
