# Generated by Django 4.2.20 on 2025-07-18 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_alcoholcategory_drinkstyle_alcoholbrand_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="alcoholbrand",
            name="name",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="drinkstyle",
            name="name",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="interest",
            name="name",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name="alcoholbrand",
            unique_together={("name", "category")},
        ),
        migrations.AlterUniqueTogether(
            name="drinkstyle",
            unique_together={("name", "category")},
        ),
        migrations.AlterUniqueTogether(
            name="interest",
            unique_together={("name", "category")},
        ),
    ]
