# Generated by Django 5.0 on 2025-08-24 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_useraccount_my_areas_useraccount_primary_area"),
    ]

    operations = [
        migrations.AddField(
            model_name="profilevisibilitysettings",
            name="my_area",
            field=models.BooleanField(default=True, verbose_name="マイエリア公開"),
        ),
    ]
