# Generated by Django 5.0 on 2025-08-24 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_profilevisibilitysettings_my_area"),
    ]

    operations = [
        migrations.AddField(
            model_name="useraccount",
            name="header_image",
            field=models.ImageField(
                blank=True, null=True, upload_to="headers", verbose_name="ヘッダー画像"
            ),
        ),
    ]
