# Generated by Django 4.2.20 on 2025-07-20 07:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("shops", "0005_atmosphereindicator_shopatmosphererating"),
        ("accounts", "0006_alter_alcoholbrand_name_alter_drinkstyle_name_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserAtmospherePreference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "score",
                    models.IntegerField(
                        help_text="-2から+2の範囲で設定", verbose_name="好みのスコア"
                    ),
                ),
                (
                    "indicator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="shops.atmosphereindicator",
                    ),
                ),
                (
                    "user_profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="atmosphere_preferences",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "ユーザー雰囲気好み",
                "verbose_name_plural": "ユーザー雰囲気好み",
                "unique_together": {("user_profile", "indicator")},
            },
        ),
    ]
