# Generated by Django 5.0 on 2025-09-01 05:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0007_useraccount_header_image"),
        ("shops", "0006_delete_welcomecontent"),
    ]

    operations = [
        migrations.CreateModel(
            name="ShopViewHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "viewed_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="閲覧日時"),
                ),
                (
                    "shop",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="view_history",
                        to="shops.shop",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="view_history",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "店舗閲覧履歴",
                "verbose_name_plural": "店舗閲覧履歴",
                "ordering": ["-viewed_at"],
                "unique_together": {("user", "shop", "viewed_at")},
            },
        ),
    ]
