# Generated by Django 4.2.20 on 2025-07-21 05:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0007_useratmospherepreference"),
    ]

    operations = [
        migrations.CreateModel(
            name="BudgetRange",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("name", models.CharField(max_length=100, unique=True)),
                ("min_price", models.IntegerField(blank=True, null=True)),
                ("max_price", models.IntegerField(blank=True, null=True)),
                ("order", models.IntegerField(default=0)),
            ],
            options={
                "verbose_name": "希望予算",
                "verbose_name_plural": "希望予算",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="DietaryPreference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("name", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True)),
            ],
            options={
                "verbose_name": "食事制限・好み",
                "verbose_name_plural": "食事制限・好み",
            },
        ),
        migrations.CreateModel(
            name="ExerciseFrequency",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("name", models.CharField(max_length=100, unique=True)),
                ("order", models.IntegerField(default=0)),
            ],
            options={
                "verbose_name": "運動頻度",
                "verbose_name_plural": "運動頻度",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="VisitPurpose",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("name", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True)),
                ("order", models.IntegerField(default=0)),
            ],
            options={
                "verbose_name": "利用目的",
                "verbose_name_plural": "利用目的",
                "ordering": ["order"],
            },
        ),
        migrations.AddField(
            model_name="useraccount",
            name="industry",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="業種"
            ),
        ),
        migrations.AddField(
            model_name="useraccount",
            name="occupation",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="職業"
            ),
        ),
        migrations.AddField(
            model_name="useraccount",
            name="position",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="役職"
            ),
        ),
        migrations.AddField(
            model_name="useraccount",
            name="budget_range",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="users",
                to="accounts.budgetrange",
            ),
        ),
        migrations.AddField(
            model_name="useraccount",
            name="dietary_preference",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="users",
                to="accounts.dietarypreference",
            ),
        ),
        migrations.AddField(
            model_name="useraccount",
            name="exercise_frequency",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="users",
                to="accounts.exercisefrequency",
            ),
        ),
        migrations.AddField(
            model_name="useraccount",
            name="visit_purposes",
            field=models.ManyToManyField(
                blank=True, related_name="users", to="accounts.visitpurpose"
            ),
        ),
    ]
