# Generated by Django 5.0 on 2025-10-13 14:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0008_shopviewhistory"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmailChangeOTP",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "new_email",
                    models.EmailField(
                        max_length=254, verbose_name="新しいメールアドレス"
                    ),
                ),
                ("otp_code", models.CharField(max_length=6, verbose_name="OTPコード")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
                ),
                (
                    "is_verified",
                    models.BooleanField(default=False, verbose_name="認証済み"),
                ),
                ("expires_at", models.DateTimeField(verbose_name="有効期限")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="email_change_otps",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "メールアドレス変更OTP",
                "verbose_name_plural": "メールアドレス変更OTP",
                "ordering": ["-created_at"],
            },
        ),
    ]
