# Generated by Django 5.0 on 2025-10-20 02:23

import django.db.models.deletion
from django.db import migrations, models


def clear_job_data(apps, schema_editor):
    """既存の職業データをクリア"""
    UserAccount = apps.get_model('accounts', 'UserAccount')
    UserAccount.objects.update(occupation=None, industry=None, position=None)


def populate_occupations(apps, schema_editor):
    """職業マスタデータ投入"""
    Occupation = apps.get_model('accounts', 'Occupation')
    occupations = [
        ("会社員（営業）", 1),
        ("会社員（事務）", 2),
        ("会社員（企画・マーケティング）", 3),
        ("会社員（技術・エンジニア）", 4),
        ("会社員（管理職）", 5),
        ("公務員", 6),
        ("教員・講師", 7),
        ("医療従事者（医師・看護師等）", 8),
        ("福祉・介護職", 9),
        ("経営者・役員", 10),
        ("個人事業主・フリーランス", 11),
        ("自営業", 12),
        ("コンサルタント", 13),
        ("士業（弁護士・税理士・会計士等）", 14),
        ("クリエイター（デザイナー・ライター等）", 15),
        ("エンジニア・プログラマー", 16),
        ("研究職", 17),
        ("販売・接客", 18),
        ("専門職（建築士・薬剤師等）", 19),
        ("学生", 20),
        ("アルバイト・パート", 21),
        ("主婦・主夫", 22),
        ("無職・求職中", 23),
        ("その他", 24),
    ]
    for name, order in occupations:
        Occupation.objects.create(name=name, order=order)


def populate_industries(apps, schema_editor):
    """業種マスタデータ投入"""
    Industry = apps.get_model('accounts', 'Industry')
    industries = [
        ("IT・通信", 1),
        ("インターネット・Web", 2),
        ("製造業（電気・電子）", 3),
        ("製造業（機械）", 4),
        ("製造業（その他）", 5),
        ("商社", 6),
        ("小売・流通", 7),
        ("金融・保険", 8),
        ("不動産・建設", 9),
        ("コンサルティング", 10),
        ("広告・マーケティング", 11),
        ("出版・メディア", 12),
        ("教育", 13),
        ("医療・福祉", 14),
        ("飲食・宿泊", 15),
        ("運輸・物流", 16),
        ("エネルギー", 17),
        ("公共サービス", 18),
        ("農業・林業・水産業", 19),
        ("芸術・エンターテイメント", 20),
        ("法律・会計", 21),
        ("人材サービス", 22),
        ("その他サービス業", 23),
        ("非営利団体・NGO", 24),
        ("その他", 25),
    ]
    for name, order in industries:
        Industry.objects.create(name=name, order=order)


def populate_positions(apps, schema_editor):
    """役職マスタデータ投入"""
    Position = apps.get_model('accounts', 'Position')
    positions = [
        ("一般社員", 1),
        ("主任", 2),
        ("係長", 3),
        ("課長", 4),
        ("次長", 5),
        ("部長", 6),
        ("本部長", 7),
        ("役員", 8),
        ("社長・代表", 9),
        ("フリーランス", 10),
        ("個人事業主", 11),
        ("学生", 12),
        ("パート・アルバイト", 13),
        ("役職なし", 14),
        ("その他", 15),
    ]
    for name, order in positions:
        Position.objects.create(name=name, order=order)


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0009_emailchangeotp"),
    ]

    operations = [
        migrations.CreateModel(
            name="Industry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="業種名"
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="説明")),
                ("order", models.IntegerField(default=0, verbose_name="表示順")),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="有効")),
            ],
            options={
                "verbose_name": "業種",
                "verbose_name_plural": "業種",
                "ordering": ["order", "name"],
            },
        ),
        migrations.CreateModel(
            name="Occupation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="職業名"
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="説明")),
                ("order", models.IntegerField(default=0, verbose_name="表示順")),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="有効")),
            ],
            options={
                "verbose_name": "職業",
                "verbose_name_plural": "職業",
                "ordering": ["order", "name"],
            },
        ),
        migrations.CreateModel(
            name="Position",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="役職名"
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="説明")),
                ("order", models.IntegerField(default=0, verbose_name="表示順")),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="有効")),
            ],
            options={
                "verbose_name": "役職",
                "verbose_name_plural": "役職",
                "ordering": ["order", "name"],
            },
        ),
        migrations.AlterField(
            model_name="useraccount",
            name="industry",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="users",
                to="accounts.industry",
                verbose_name="業種",
            ),
        ),
        migrations.AlterField(
            model_name="useraccount",
            name="occupation",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="users",
                to="accounts.occupation",
                verbose_name="職業",
            ),
        ),
        migrations.AlterField(
            model_name="useraccount",
            name="position",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="users",
                to="accounts.position",
                verbose_name="役職",
            ),
        ),
        # 既存データクリア
        migrations.RunPython(clear_job_data, reverse_code=migrations.RunPython.noop),
        # マスタデータ投入
        migrations.RunPython(populate_occupations, reverse_code=migrations.RunPython.noop),
        migrations.RunPython(populate_industries, reverse_code=migrations.RunPython.noop),
        migrations.RunPython(populate_positions, reverse_code=migrations.RunPython.noop),
    ]
