import type { Metadata } from "next";
import "./globals.css";
import Provider from "@/app/Provider";
import React from "react";
import styles from './style.module.scss';

export const metadata: Metadata = {
  title: "GARDEN",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
    return (
        <html lang="ja">
            <body>
                <Provider>
                    <main>{children}</main>
                </Provider>
            </body>
        </html>
    );
}
