# Generated by Django 5.0 on 2025-08-16 13:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shops", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Area",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="エリア名")),
                (
                    "name_kana",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="エリア名（カナ）"
                    ),
                ),
                (
                    "area_type",
                    models.CharField(
                        choices=[
                            ("prefecture", "都道府県"),
                            ("city", "市区町村"),
                            ("ward", "区"),
                            ("district", "地区"),
                            ("neighborhood", "町域"),
                            ("custom", "カスタムエリア"),
                        ],
                        max_length=20,
                        verbose_name="エリアタイプ",
                    ),
                ),
                (
                    "level",
                    models.IntegerField(
                        default=0,
                        help_text="0:都道府県, 1:市区町村, 2:区, 3:地区, 4:町域",
                        verbose_name="階層レベル",
                    ),
                ),
                (
                    "geometry",
                    models.TextField(
                        blank=True,
                        help_text="GeoJSON形式",
                        null=True,
                        verbose_name="ポリゴンジオメトリ",
                    ),
                ),
                (
                    "center_point",
                    models.TextField(
                        blank=True,
                        help_text="緯度,経度",
                        null=True,
                        verbose_name="中心点",
                    ),
                ),
                (
                    "postal_code",
                    models.CharField(
                        blank=True, max_length=10, verbose_name="郵便番号"
                    ),
                ),
                (
                    "jis_code",
                    models.CharField(
                        blank=True,
                        help_text="行政区域コード",
                        max_length=10,
                        verbose_name="JISコード",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="有効")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成日"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_areas",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="作成者",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="shops.area",
                        verbose_name="親エリア",
                    ),
                ),
            ],
            options={
                "verbose_name": "エリア",
                "verbose_name_plural": "エリア",
                "ordering": ["level", "name"],
            },
        ),
        migrations.AlterField(
            model_name="shop",
            name="area",
            field=models.ForeignKey(
                blank=True,
                help_text="店舗が所属する地理的エリア",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="shops",
                to="shops.area",
                verbose_name="所属エリア",
            ),
        ),
        migrations.AddIndex(
            model_name="area",
            index=models.Index(
                fields=["area_type", "level"], name="shops_area_area_ty_abbe14_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="area",
            index=models.Index(
                fields=["parent", "is_active"], name="shops_area_parent__00262c_idx"
            ),
        ),
    ]
