# Generated by Django 5.0 on 2025-05-20 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shops", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="shoptag",
            name="reaction_count",
            field=models.IntegerField(default=0),
        ),
    ]
