# Generated by Django 5.0 on 2025-08-17 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shops", "0002_area_alter_shop_area_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="area",
            name="center_point",
            field=models.TextField(
                blank=True,
                help_text="緯度,経度（カンマ区切り）",
                null=True,
                verbose_name="中心点",
            ),
        ),
        migrations.AlterField(
            model_name="area",
            name="geometry",
            field=models.TextField(
                blank=True,
                help_text="GeoJSON形式のジオメトリデータ",
                null=True,
                verbose_name="ポリゴンジオメトリ",
            ),
        ),
    ]
