# Generated by Django 5.0 on 2025-05-30 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shops", "0003_remove_shoptag_reaction_count"),
    ]

    operations = [
        migrations.CreateModel(
            name="PaymentMethod",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name="shop",
            name="access",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="shop",
            name="phone_number",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="shop",
            name="payment_methods",
            field=models.ManyToManyField(
                blank=True, related_name="shops", to="shops.paymentmethod"
            ),
        ),
    ]
