# Generated by Django 5.0 on 2025-08-25 02:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shops", "0003_alter_area_center_point_alter_area_geometry"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="shopatmosphererating",
            options={},
        ),
        migrations.AlterUniqueTogether(
            name="shopatmosphererating",
            unique_together=set(),
        ),
        migrations.CreateModel(
            name="ShopAtmosphereAggregate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "atmosphere_averages",
                    models.JSONField(
                        default=dict,
                        help_text="指標IDをキー、平均スコアを値とする辞書",
                        verbose_name="雰囲気平均値",
                    ),
                ),
                (
                    "total_feedbacks",
                    models.IntegerField(default=0, verbose_name="総フィードバック数"),
                ),
                (
                    "last_updated",
                    models.DateTimeField(auto_now=True, verbose_name="最終更新日時"),
                ),
                (
                    "shop",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="atmosphere_aggregate",
                        to="shops.shop",
                        verbose_name="店舗",
                    ),
                ),
            ],
            options={
                "verbose_name": "店舗雰囲気集計データ",
                "verbose_name_plural": "店舗雰囲気集計データ",
            },
        ),
        migrations.CreateModel(
            name="ShopAtmosphereFeedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "atmosphere_scores",
                    models.JSONField(
                        default=dict,
                        help_text="指標ID をキー、スコア(-2~+2)を値とする辞書",
                        verbose_name="雰囲気スコア",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
                (
                    "shop",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="atmosphere_feedbacks",
                        to="shops.shop",
                        verbose_name="店舗",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="atmosphere_feedbacks",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="評価者",
                    ),
                ),
            ],
            options={
                "verbose_name": "店舗雰囲気フィードバック",
                "verbose_name_plural": "店舗雰囲気フィードバック",
                "ordering": ["-updated_at"],
                "unique_together": {("user", "shop")},
            },
        ),
    ]
