# Generated by Django 4.2.20 on 2025-07-20 07:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("shops", "0004_paymentmethod_shop_access_shop_phone_number_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AtmosphereIndicator",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="指標名"
                    ),
                ),
                (
                    "description_left",
                    models.CharField(
                        help_text="スコア-2の表現 例：静かに過ごす",
                        max_length=100,
                        verbose_name="左端の表現",
                    ),
                ),
                (
                    "description_right",
                    models.CharField(
                        help_text="スコア+2の表現 例：会話を楽しむ",
                        max_length=100,
                        verbose_name="右端の表現",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="ShopAtmosphereRating",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "score",
                    models.IntegerField(
                        help_text="-2から+2の範囲で評価", verbose_name="評価スコア"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "indicator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="shops.atmosphereindicator",
                    ),
                ),
                (
                    "shop",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="atmosphere_ratings",
                        to="shops.shop",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "店舗雰囲気評価",
                "verbose_name_plural": "店舗雰囲気評価",
                "unique_together": {("shop", "indicator", "user")},
            },
        ),
    ]
