# Generated by Django 5.0 on 2025-08-30 05:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shops", "0004_alter_shopatmosphererating_options_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="WelcomeContent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "content_type",
                    models.CharField(
                        choices=[
                            ("MESSAGE", "ウェルカムメッセージ"),
                            ("TIP", "お店のヒント"),
                        ],
                        default="MESSAGE",
                        max_length=10,
                        verbose_name="種別",
                    ),
                ),
                ("text", models.TextField(max_length=200, verbose_name="本文")),
                (
                    "is_anonymous",
                    models.BooleanField(default=False, verbose_name="匿名投稿"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="投稿日"),
                ),
                (
                    "shop",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="welcome_contents",
                        to="shops.shop",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="posted_contents",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "歓迎コンテンツ",
                "verbose_name_plural": "歓迎コンテンツ",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="WelcomeAction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="歓迎日"),
                ),
                (
                    "shop",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="welcome_actions",
                        to="shops.shop",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="welcomed_actions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "歓迎アクション",
                "verbose_name_plural": "歓迎アクション",
                "unique_together": {("user", "shop")},
            },
        ),
    ]
