# Generated by Django 5.0 on 2025-07-27 12:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shops", "0005_atmosphereindicator_shopatmosphererating"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="shopupdatereaction",
            name="shop_update_log",
        ),
        migrations.RemoveField(
            model_name="shopupdatereaction",
            name="user",
        ),
        migrations.AddField(
            model_name="shop",
            name="budget_note",
            field=models.TextField(
                blank=True, help_text="予算に関する補足情報", null=True
            ),
        ),
        migrations.AddField(
            model_name="shop",
            name="budget_weekday_max",
            field=models.IntegerField(
                blank=True, help_text="平日の最高予算", null=True
            ),
        ),
        migrations.AddField(
            model_name="shop",
            name="budget_weekday_min",
            field=models.IntegerField(
                blank=True, help_text="平日の最低予算", null=True
            ),
        ),
        migrations.AddField(
            model_name="shop",
            name="budget_weekend_max",
            field=models.IntegerField(
                blank=True, help_text="週末の最高予算", null=True
            ),
        ),
        migrations.AddField(
            model_name="shop",
            name="budget_weekend_min",
            field=models.IntegerField(
                blank=True, help_text="週末の最低予算", null=True
            ),
        ),
        migrations.CreateModel(
            name="ShopEditHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "field_name",
                    models.CharField(
                        help_text="編集されたフィールド名", max_length=100
                    ),
                ),
                (
                    "old_value",
                    models.TextField(blank=True, help_text="変更前の値", null=True),
                ),
                (
                    "new_value",
                    models.TextField(blank=True, help_text="変更後の値", null=True),
                ),
                ("edited_at", models.DateTimeField(auto_now_add=True)),
                (
                    "shop",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="edit_histories",
                        to="shops.shop",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="shop_edit_histories",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-edited_at"],
            },
        ),
        migrations.CreateModel(
            name="HistoryEvaluation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "evaluation",
                    models.CharField(
                        choices=[("GOOD", "Good"), ("BAD", "Bad")], max_length=4
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="history_evaluations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "history",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="evaluations",
                        to="shops.shopedithistory",
                    ),
                ),
            ],
            options={
                "unique_together": {("history", "user")},
            },
        ),
        migrations.DeleteModel(
            name="ShopUpdateLog",
        ),
        migrations.DeleteModel(
            name="ShopUpdateReaction",
        ),
    ]
