# Generated by Django 5.0 on 2025-08-30 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shops", "0005_add_welcome_functionality"),
    ]

    operations = [
        migrations.DeleteModel(
            name="WelcomeContent",
        ),
    ]
