# Generated by Django 5.0 on 2025-10-04 04:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0008_shopviewhistory"),
        ("shops", "0006_delete_welcomecontent"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RegularUsageScene",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="記録日"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日"),
                ),
                (
                    "shop",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="regular_usage_scenes",
                        to="shops.shop",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="regular_usage_scenes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "visit_purposes",
                    models.ManyToManyField(
                        related_name="regular_usage_scenes",
                        to="accounts.visitpurpose",
                        verbose_name="利用目的",
                    ),
                ),
            ],
            options={
                "verbose_name": "常連利用シーン",
                "verbose_name_plural": "常連利用シーン",
                "unique_together": {("user", "shop")},
            },
        ),
    ]
