# Generated by Django 5.0 on 2025-10-04 10:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0008_shopviewhistory"),
        ("shops", "0007_regularusagescene"),
    ]

    operations = [
        migrations.CreateModel(
            name="ShopRegularStatistics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "age_gender_summary",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="年代・性別サマリー"
                    ),
                ),
                (
                    "atmosphere_tendency",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("solitude", "一人の時間を重視"),
                            ("flexible", "フレキシブル"),
                            ("community", "コミュニティを重視"),
                        ],
                        max_length=20,
                        null=True,
                        verbose_name="雰囲気傾向",
                    ),
                ),
                (
                    "atmosphere_tendency_percentage",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="雰囲気傾向の割合",
                    ),
                ),
                (
                    "atmosphere_distribution",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="雰囲気分布データ"
                    ),
                ),
                (
                    "visit_purpose_distribution",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="利用目的分布"
                    ),
                ),
                (
                    "regular_count",
                    models.IntegerField(default=0, verbose_name="常連数"),
                ),
                (
                    "last_calculated",
                    models.DateTimeField(auto_now=True, verbose_name="最終計算日時"),
                ),
                (
                    "popular_visit_purpose",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="accounts.visitpurpose",
                        verbose_name="人気の利用目的",
                    ),
                ),
                (
                    "shop",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="regular_statistics",
                        to="shops.shop",
                    ),
                ),
            ],
            options={
                "verbose_name": "店舗常連統計",
                "verbose_name_plural": "店舗常連統計",
            },
        ),
    ]
