# Generated by Django 5.0 on 2025-10-13 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shops", "0008_shopregularstatistics"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shop",
            name="access",
            field=models.TextField(blank=True, null=True, verbose_name="アクセス情報"),
        ),
        migrations.AlterField(
            model_name="shop",
            name="address",
            field=models.CharField(max_length=255, verbose_name="住所"),
        ),
        migrations.AlterField(
            model_name="shop",
            name="budget_note",
            field=models.TextField(
                blank=True,
                help_text="予算に関する補足情報",
                null=True,
                verbose_name="予算メモ",
            ),
        ),
        migrations.AlterField(
            model_name="shop",
            name="budget_weekday_max",
            field=models.IntegerField(
                blank=True,
                help_text="平日の最高予算",
                null=True,
                verbose_name="平日予算（最高）",
            ),
        ),
        migrations.AlterField(
            model_name="shop",
            name="budget_weekday_min",
            field=models.IntegerField(
                blank=True,
                help_text="平日の最低予算",
                null=True,
                verbose_name="平日予算（最低）",
            ),
        ),
        migrations.AlterField(
            model_name="shop",
            name="budget_weekend_max",
            field=models.IntegerField(
                blank=True,
                help_text="週末の最高予算",
                null=True,
                verbose_name="週末予算（最高）",
            ),
        ),
        migrations.AlterField(
            model_name="shop",
            name="budget_weekend_min",
            field=models.IntegerField(
                blank=True,
                help_text="週末の最低予算",
                null=True,
                verbose_name="週末予算（最低）",
            ),
        ),
        migrations.AlterField(
            model_name="shop",
            name="building",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="建物名"
            ),
        ),
        migrations.AlterField(
            model_name="shop",
            name="capacity",
            field=models.IntegerField(
                blank=True, default=0, null=True, verbose_name="収容人数"
            ),
        ),
        migrations.AlterField(
            model_name="shop",
            name="city",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="市区町村"
            ),
        ),
        migrations.AlterField(
            model_name="shop",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
        ),
        migrations.AlterField(
            model_name="shop",
            name="name",
            field=models.CharField(max_length=100, verbose_name="店舗名"),
        ),
        migrations.AlterField(
            model_name="shop",
            name="phone_number",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="電話番号"
            ),
        ),
        migrations.AlterField(
            model_name="shop",
            name="prefecture",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="都道府県"
            ),
        ),
        migrations.AlterField(
            model_name="shop",
            name="street",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="町名・番地"
            ),
        ),
        migrations.AlterField(
            model_name="shop",
            name="zip_code",
            field=models.CharField(
                blank=True, max_length=10, null=True, verbose_name="郵便番号"
            ),
        ),
    ]
