# Generated by Django 5.0 on 2025-10-19 08:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shops", "0009_alter_shop_access_alter_shop_address_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ContactSubmission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "contact_type",
                    models.CharField(
                        choices=[
                            ("report", "報告"),
                            ("inquiry", "問い合わせ"),
                            ("request", "要望"),
                        ],
                        max_length=20,
                        verbose_name="問い合わせ種別",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("shop_closed", "店舗閉店・休店・移転"),
                            ("inappropriate_image", "不適切な店舗画像"),
                            ("inappropriate_review", "不適切な口コミ"),
                            ("inappropriate_tag", "不適切な印象タグ"),
                            ("malicious_user", "悪質ユーザー"),
                            ("how_to_use", "使い方"),
                            ("account_privacy", "アカウント・プライバシー"),
                            ("technical_issue", "技術的問題・バグ"),
                            ("other_inquiry", "その他の問い合わせ"),
                            ("new_feature", "新機能要望"),
                            ("improvement", "既存機能改善"),
                            ("design_ux", "デザイン・UI/UX"),
                            ("other_request", "その他の要望"),
                        ],
                        max_length=50,
                        verbose_name="カテゴリ",
                    ),
                ),
                ("subject", models.CharField(max_length=200, verbose_name="件名")),
                ("description", models.TextField(verbose_name="詳細説明")),
                (
                    "screenshot",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="contact_screenshots/",
                        verbose_name="スクリーンショット",
                    ),
                ),
                (
                    "contact_email",
                    models.EmailField(
                        blank=True,
                        max_length=254,
                        null=True,
                        verbose_name="連絡先メールアドレス",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "未対応"),
                            ("in_progress", "対応中"),
                            ("resolved", "解決済み"),
                            ("closed", "クローズ"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="対応状況",
                    ),
                ),
                ("admin_note", models.TextField(blank=True, verbose_name="管理者メモ")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
                (
                    "resolved_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="解決日時"
                    ),
                ),
                (
                    "image",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="shops.shopimage",
                        verbose_name="関連画像",
                    ),
                ),
                (
                    "reported_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reports_against",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="報告対象ユーザー",
                    ),
                ),
                (
                    "review",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="shops.shopreview",
                        verbose_name="関連口コミ",
                    ),
                ),
                (
                    "shop",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="shops.shop",
                        verbose_name="関連店舗",
                    ),
                ),
                (
                    "tag",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="shops.shoptag",
                        verbose_name="関連タグ",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="送信者",
                    ),
                ),
            ],
            options={
                "verbose_name": "問い合わせ",
                "verbose_name_plural": "問い合わせ",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["contact_type", "status"],
                        name="shops_conta_contact_1e0a94_idx",
                    ),
                    models.Index(
                        fields=["user", "created_at"],
                        name="shops_conta_user_id_b6b57c_idx",
                    ),
                ],
            },
        ),
    ]
